export const Skill_data = [
    {
      skill_name: "Html 5",
      Image: "/html.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Css",
      Image: "/css.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Java Script",
      Image: "/js.png",
      width: 65,
      height: 65,
    },
    {
      skill_name: "Tailwind Css",
      Image: "/tailwind.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "React",
      Image: "/react.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Redux",
      Image: "/redux.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "React Query",
      Image: "/reactquery.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Type Script",
      Image: "/ts.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Next js 13",
      Image: "/next.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Framer Motion",
      Image: "/framer.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Stripe Payment",
      Image: "/stripe.webp",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Node js",
      Image: "/node-js.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Mongo db",
      Image: "/mongodb.png",
      width: 40,
      height: 40,
    },

  ];

  export const Socials = [
    {
      name: "Github",
      src: "/gitwhite.png",
      url: "https://github.com/danabestun"
    },
    {
      name: "Instagram",
      src: "/instagram.svg",
      url: "https://www.instagram.com/danabestun/"
    },
    {
      name: "Facebook",
      src: "/facebook.svg",
      url: "https://www.facebook.com/profile.php?id=100080809302441"
    }
  ];


  export const AllSkills = [
    // Frontend Skills
    ...[
      {
        skill_name: "HTML 5",
        Image: "/html.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "CSS",
        Image: "/css.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "JavaScript",
        Image: "/js.png",
        width: 65,
        height: 65,
        category: "Frontend",
      },
      {
        skill_name: "Tailwind CSS",
        Image: "/tailwind.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "Material UI",
        Image: "/mui.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "React",
        Image: "/react.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "Redux",
        Image: "/redux.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "React Query",
        Image: "/reactquery.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "TypeScript",
        Image: "/ts.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "Next.js 13",
        Image: "/next.png",
        width: 80,
        height: 80,
        category: "Frontend",
      },
      {
        skill_name: "Vue.js",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
        width: 70,
        height: 70,
        category: "Frontend",
      },
      {
        skill_name: "Angular",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg",
        width: 70,
        height: 70,
        category: "Frontend",
      },
      {
        skill_name: "Svelte",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/svelte/svelte-original.svg",
        width: 70,
        height: 70,
        category: "Frontend",
      },
    ],
    // Backend Skills
    ...[
      {
        skill_name: "Node.js",
        Image: "/node-js.png",
        width: 80,
        height: 80,
        category: "Backend",
      },
      {
        skill_name: "Express.js",
        Image: "/express.png",
        width: 80,
        height: 80,
        category: "Backend",
      },
      {
        skill_name: "PHP",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-plain.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "MongoDB",
        Image: "/mongodb.png",
        width: 40,
        height: 40,
        category: "Backend",
      },
      {
        skill_name: "PostgreSQL",
        Image: "/postger.png",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "MySQL",
        Image: "/mysql.png",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Prisma",
        Image: "/prisma.webp",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Rust",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/rust/rust-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: ".NET",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-plain.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "NestJS",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nestjs/nestjs-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Go",
        Image: "/go.png",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Python",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Django",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "FastAPI",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fastapi/fastapi-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Java",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Laravel",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/laravel/laravel-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Firebase",
        Image: "/Firebase.png",
        width: 70,
        height: 70,
        category: "Backend",
      },
      {
        skill_name: "Supabase",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/supabase/supabase-original.svg",
        width: 70,
        height: 70,
        category: "Backend",
      },
    ],
    // DevOps Skills
    ...[
      {
        skill_name: "Docker",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Kubernetes",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "GitHub Actions",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Jenkins",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-line.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "AWS",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-plain-wordmark.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Azure",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-plain.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Google Cloud",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Vercel",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vercel/vercel-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Heroku",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/heroku/heroku-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Railway",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/railway/railway-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "DigitalOcean",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/digitalocean/digitalocean-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Terraform",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Ansible",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ansible/ansible-original.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Jira",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-plain-wordmark.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
      {
        skill_name: "Linear",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linear/linear-plain.svg",
        width: 70,
        height: 70,
        category: "DevOps",
      },
    ],
    // Full Stack / Other Skills
    ...[
      {
        skill_name: "WordPress",
        Image: "/Wordpress.png",
        width: 80,
        height: 80,
        category: "Full Stack",
      },
      {
        skill_name: "GraphQL",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "Socket.io",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/socketio/socketio-original.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "Redis",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "Git",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "Linux",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "Figma",
        Image: "/figma.png",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "AI Agents",
        Image: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "TensorFlow",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
      {
        skill_name: "PyTorch",
        Image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg",
        width: 70,
        height: 70,
        category: "Full Stack",
      },
    ],
  ].map((skill, index) => ({ ...skill, id: index + 1 }));


